programs:
  echo_test:
    cmd: "ech 'Hello, Taskmaster!'"
    numprocs: 2
    umask: "022"
    workingdir: .
    autostart: True
    autorestart: unexpected
    startretries: 3
    stopsignal: TERM
    stoptime: 0
    stdout: result/echo_test.stdout
    stderr: result/echo_test.stderr
    env:
      TEST_VAR: "test_value"
#programs:
  sleep_test:
    cmd: "sleep 60"
    numprocs: 1
    umask: "022"
    workingdir: .
    autostart: false
    autorestart: never
    exitcodes:
      - 0
    startretries: 4
    starttime: 1
    stopsignal: TERM
    stoptime: 0
    stdout: result/sleep_test.stdout
    stderr: result/sleep_test.stderr
#
#  fast_exit:
#    cmd: "exit 1"
#    numprocs: 1
#    umask: "022"
#    workingdir: .
#    autostart: true
#    autorestart: always
#    exitcodes:
#      - 0
#    startretries: 3
#    starttime: 1
#    stopsignal: TERM
#    stoptime: 1
#    stdout: result/fast_exit.stdout
#    stderr: result/fast_exit.stderr
#
#  custom_env:
#    cmd: "env"
#    numprocs: 1
#    umask: "027"
#    workingdir: /tmp
#    autostart: true
#    autorestart: never
#    exitcodes:
#      - 0
#    startretries: 1
#    starttime: 1
#    stopsignal: HUP
#    stoptime: 1
#    stdout: result/custom_env.stdout
#    stderr: result/custom_env.stderr
#    env:
#      CUSTOM_VAR: "custom_value"
#      PATH: "/custom/path:$PATH"
